spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clean-architecture-lecture
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    generate-ddl: on
    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace